- src/components/molecules/Pagination/Pagination.stories.tsx
- src/components/molecules/Pagination/Pagination.tsx
Change old default size for large and update the default size to 34px
> refactor(molecules/pagination): Add large size

- src/components/atoms/Checkbox/Checkbox.tsx
- src/components/atoms/Radio/Radio.tsx
- src/components/atoms/Select/Select.tsx
- src/components/molecules/Container/Container.tsx
- src/components/molecules/Modal/Modal.tsx
* fix modal
* fix title container
* fix color radio
* fix position button when outlined
* fix checkbox
> fix(aiq-design-system): small fixes

- package.json
- src/components/molecules/Breadcrumb/Breadcrumb.stories.tsx
- src/components/molecules/Breadcrumb/Breadcrumb.test.tsx
- src/components/molecules/Breadcrumb/Breadcrumb.tsx
- src/components/molecules/Sidebar/Item.tsx
- src/components/molecules/Sidebar/SubItens.tsx
showHome was removed because of components internationalization
> fix(molecules-breadcrumb): remove showHome

- src/components/molecules/Sidebar/Item.tsx
active item when location is match
> feat(aiq-design-system): Active Item Sidebar

- src/components/atoms/Checkbox/Checkbox.tsx
- src/components/molecules/Tab/Tab.tsx
Allow to user change internally the check state
> fix(checkbox): fix control of isChecked

- src/components/atoms/Select/Select.tsx
* fix(select): fix autocomplete prop variant
* fix(select): fix space when variant is outilined
> fix(Select): small fixes

- src/components/molecules/Pagination/Pagination.stories.tsx
- src/components/molecules/Pagination/Pagination.tsx
* fix(molecules/pagination): fix init on 1 and variantion 'noTotal'
* fix(molecules/pagination): change variation name
* fix(molecules/pagination): change variation name
> Fix/pagination (#137)

- .github/workflows/run-tests.yml
- .gitignore
work created to run tests automatically using Github Actions when creating pull requests
> run tests automatically

- package.json
- src/components/Modal/Modal.stories.tsx
* 0.5.22
* Develop (#226)
* fix(steps): staeps and table usage (#224)
* chore(aiq-design-system): updade libs (#225)
Co-authored-by: Felipe Cesar Maccari <felipecesarmaccari@gmail.com>
* 0.5.23
* feat(alert): add alert component
* 0.5.24
* 0.5.24
* Update Modal.stories.tsx
Co-authored-by: FelipeMaccari <gh-actions-FelipeMaccari@github.com>
Co-authored-by: Felipe Cesar Maccari <felipecesarmaccari@gmail.com>
Co-authored-by: vitorCamargo <gh-actions-vitorCamargo@github.com>
> fix(modal-stories): removing alert variant (#229)

- src/components/Button/Button.tsx
- src/components/Drawer/Drawer.tsx
* Update Drawer.tsx
* fix(button): add border props
Co-authored-by: Vitor Bueno <vitorbueno@aiqfome.com>
> Update Drawer.tsx (#276)

- src/components/TimePicker/TimePicker.tsx
Reverts aiqfome/aiq-design-system#279
> Revert "Develop"

- src/components/Modal/Modal.tsx
* fix(visual): change input and toast components
* fix(select): font and props
* fix cursor type
* fix(tests): fix all input tests
* fix(select): fix borders
* Update Modal.tsx
Co-authored-by: Vitor Bueno <vitorbueno@aiqfome.com>
> Fix/visual general (#281)

- src/components/Button/Button.tsx
- src/components/Multistep/Multistep.tsx
- src/components/Popover/Popover.tsx
- src/components/Table/Table.tsx
* fix(popover): able to change visible manually
* fix(table): add onHoverRow
* fix(popover): add onChangeVisibility on Popover
* refactor(button): add error button
* fix(multistep): allow propos on step button
Co-authored-by: Vitor Bueno <vitorbueno@aiqfome.com>
> Fix/popover visibility (#287)

- package.json
- src/components/Container/Container.tsx
- src/components/TimePicker/TimePicker.tsx
* Develop (#270)
* fix(visual): change input and toast components (#268)
* fix(visual): change input and toast components
* fix(select): font and props
* fix cursor type
* fix(tests): fix all input tests
* fix(select): fix borders
* fix(tooltip): remove some default styles (#269)
* feat(popover): ajust popover styles (#267)
* feat(popover): ajust popover styles
* feat(popover): add conditional styling to global style
* feat(popover): ajust color props
Co-authored-by: Felipe Cesar Maccari <felipecesarmaccari@gmail.com>
* 0.5.39
* Develop (#272)
* fix(visual): change input and toast components (#268)
* fix(visual): change input and toast components
* fix(select): font and props
* fix cursor type
* fix(tests): fix all input tests
* fix(select): fix borders
* fix(tooltip): remove some default …
> Fix/container size (#298)

- src/components/Input/Input.tsx
- src/components/TimePicker/TimePicker.tsx
- src/global/popover.js
* fix(timePicker): add sufix input props
* fix(popover): placement fixed on large widths
> Fix/input sufix on time picker (#302)

- src/components/Actions/Actions.tsx
- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
- src/components/Table/TableRow.tsx
* fix(Actions): add actions disabled item
* fix(Table): add table expanded row automatic
> Feat/table render expanded automatic (#308)

- src/components/Multistep/Multistep.tsx
- src/components/Sidebar/SubItens.tsx
* fix(sidebar): fiz font size
* fix(steps): fix steps alignment
> Fix/timeline alignment (#316)

- package.json
- src/components/Alert/Alert.tsx
- src/components/Modal/Modal.tsx
- src/components/MultiSelect/MultiSelect.tsx
- src/components/MultiSelect/MultiSelectFetchable.tsx
- src/components/MultiSelect/MultiSelectStatic.tsx
- src/components/TimePicker/TimePicker.stories.tsx
- src/components/TimePicker/TimePicker.tsx
- src/components/TimePicker/TimePickerAll.tsx
- src/components/TimePicker/TimePickerMinSec.tsx
- yarn.lock
* fix(multiselect): add click function for filters
* Update package.json
* fix(timepicker): add change value for input
* Update Modal.tsx
* Update Alert.tsx
* Update Modal.tsx
> Fix/multiselect all options (#361)

- .github/workflows/npm-publish.yml
* Develop (#390)
* chore(storybook): upgrade storybook (#380)
* chore(core): add feature request form to issues (#382)
* Fix/code warnings (#385)
* fix(actions): remove implicit validation
* feat(input-outlined): remove implicit validation
* fix(sidebar): fix identical operands
* feat(sidebar): remove unused import
* feat(table-head): remove unused imports
* feat(tooltip): remove unused import
* feat(table-head): remove proptypes
* refactor(sidebar): rename items props (#387)
* Fix/pack version (#389)
* Develop (#386)
* chore(storybook): upgrade storybook (#380)
* chore(core): add feature request form to issues (#382)
* Fix/code warnings (#385)
* fix(actions): remove implicit validation
* feat(input-outlined): remove implicit validation
* fix(sidebar): fix identical operands
* …
> Hotfix/change node version npm publish (#458)

- src/components/MultiSelect/MultiSelect.test.tsx
- src/components/MultiSelect/MultiSelect.tsx
- src/components/MultiSelect/MultiSelectFetchable.tsx
- src/components/MultiSelect/MultiSelectStatic.tsx
- yarn.lock
- add color prop
- remove divider when filters prop is empty
> feat(multi-select): add color prop
